import { LoaderCircle, UserMinus } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/field";
import type {
  ManageableJobSummary,
  ManageableOrganizationSummary,
  Organization,
  OrganizationInvitation,
  OrganizationMembershipInvitation,
} from "@/lib/recruitment-api";

type OrganizationCreateInput = {
  slug: string;
  name: string;
  description: string;
  websiteUrl: string;
};

export function OrganizationActions({ busy, inspect, create }: { busy: string | null; inspect: (slug: string) => Promise<void>; create: (input: OrganizationCreateInput) => Promise<void> }) {
  const [slug, setSlug] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [websiteUrl, setWebsiteUrl] = useState(""); const [attested, setAttested] = useState(false); return <section className="rounded-[1.5rem] border border-white/10 bg-panel p-5"><h2 className="text-xl font-semibold text-white">Open or establish an organization</h2><form className="mt-5" onSubmit={(event) => { event.preventDefault(); void inspect(slug); }}><label className="text-sm font-semibold text-white">Existing organization slug<Input className="mt-1.5" value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="organization-slug" required /></label><Button variant="secondary" className="mt-3" type="submit" disabled={busy !== null}>{busy === "organization-load" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Open authorized organization</Button></form><div className="my-6 border-t border-white/10" /><form onSubmit={(event) => { event.preventDefault(); void create({ slug, name, description, websiteUrl }); }}><h3 className="font-semibold text-white">Establish a private organization</h3><label className="mt-3 block text-sm text-white">Slug<Input className="mt-1.5" value={slug} onChange={(event) => setSlug(event.target.value.toLowerCase().replace(/\s+/gu, "-"))} required /></label><label className="mt-3 block text-sm text-white">Name<Input className="mt-1.5" value={name} onChange={(event) => setName(event.target.value)} required /></label><label className="mt-3 block text-sm text-white">Description<Textarea className="mt-1.5" value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="mt-3 block text-sm text-white">Website (optional)<Input className="mt-1.5" type="url" value={websiteUrl} onChange={(event) => setWebsiteUrl(event.target.value)} /></label><label className="mt-4 flex gap-3 text-sm leading-6 text-mist"><input type="checkbox" className="mt-1 size-4 accent-acid" checked={attested} onChange={(event) => setAttested(event.target.checked)} /><span>I am the signed-in human authorized to establish this mandate. It will be private and unverified.</span></label><Button className="mt-4 w-full" type="submit" disabled={busy !== null || !attested || !slug || !name}>Create private unverified organization</Button></form></section>; }
export function ManageableOrganizationInventory({ items, loaded, loadFailed, nextCursor, moreLoading, busy, retry, loadOlder, open }: { items: ManageableOrganizationSummary[]; loaded: boolean; loadFailed: boolean; nextCursor: string | null; moreLoading: boolean; busy: string | null; retry: () => void; loadOlder: () => void; open: (summary: ManageableOrganizationSummary) => void }) {
  const initialLoading = !loaded && !loadFailed;
  return <section className="rounded-[1.5rem] border border-acid/20 bg-acid/[.035] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Private inventory</p><h2 className="mt-2 text-xl font-semibold text-white">Organizations I manage</h2><p className="mt-1 text-sm leading-6 text-mist">Owner and admin summaries only. Open a summary to load the exact authorized organization record before any mutation.</p></div>{loadFailed && <Button variant="secondary" onClick={retry}>Retry organizations</Button>}</div>{initialLoading && <p role="status" className="mt-5 text-sm text-mist">Loading organizations you manage…</p>}{loadFailed && !loaded && <p role="alert" className="mt-5 rounded-xl border border-amber-300/25 bg-amber-300/[.08] p-3 text-sm leading-6 text-amber-100">Organizations could not be loaded. No empty state is assumed; retry when the private inventory is available.</p>}{loaded && items.length === 0 && <p className="mt-5 text-sm text-mist">No manageable organizations were returned for this signed-in human.</p>}{loaded && items.length > 0 && <ol className="mt-5 space-y-3">{items.map((summary) => <li key={summary.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">{summary.name}</p><p className="mt-1 text-xs text-mist">{summary.slug} · {summary.managementRole} · {summary.visibility} · updated {formatDate(summary.updatedAt)}</p><p className="mt-1 text-xs text-mist">{summary.recruitingVerificationActive ? "Recruiting control active" : "Recruiting control inactive"}</p></div><Button variant="secondary" disabled={busy !== null} onClick={() => open(summary)}>{busy === "organization-load" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Open organization</Button></div></li>)}</ol>}{loaded && nextCursor && <Button variant="secondary" className="mt-4" disabled={busy !== null || moreLoading} onClick={loadOlder}>{moreLoading && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Load more organizations</Button>}</section>;
}

export function ManageableJobInventory({ items, loaded, loadFailed, nextCursor, moreLoading, busy, retry, loadOlder, open }: { items: ManageableJobSummary[]; loaded: boolean; loadFailed: boolean; nextCursor: string | null; moreLoading: boolean; busy: string | null; retry: () => void; loadOlder: () => void; open: (summary: ManageableJobSummary) => void }) {
  const initialLoading = !loaded && !loadFailed;
  return <section className="rounded-[1.5rem] border border-acid/20 bg-acid/[.035] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Private inventory</p><h2 className="mt-2 text-xl font-semibold text-white">Jobs I manage</h2><p className="mt-1 text-sm leading-6 text-mist">Job summaries are discovery only. Opening a job loads its exact organization and job resources before edits or lifecycle actions.</p></div>{loadFailed && <Button variant="secondary" onClick={retry}>Retry jobs</Button>}</div>{initialLoading && <p role="status" className="mt-5 text-sm text-mist">Loading jobs you manage…</p>}{loadFailed && !loaded && <p role="alert" className="mt-5 rounded-xl border border-amber-300/25 bg-amber-300/[.08] p-3 text-sm leading-6 text-amber-100">Jobs could not be loaded. No empty state is assumed; retry when the private inventory is available.</p>}{loaded && items.length === 0 && <p className="mt-5 text-sm text-mist">No manageable jobs were returned for this signed-in human.</p>}{loaded && items.length > 0 && <ol className="mt-5 space-y-3">{items.map((summary) => <li key={summary.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">{summary.title}</p><p className="mt-1 text-xs text-mist">{summary.organizationName} · {summary.organizationSlug}/{summary.slug}</p><p className="mt-1 text-xs text-mist">{summary.managementRole} · {summary.status}{summary.location ? ` · ${summary.location}` : ""}{summary.workMode ? ` · ${summary.workMode.replace("_", "-")}` : ""}{summary.employmentType ? ` · ${summary.employmentType.replaceAll("_", " ")}` : ""} · updated {formatDate(summary.updatedAt)}</p></div><Button variant="secondary" disabled={busy !== null} onClick={() => open(summary)}>{busy === "job-load" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Open job</Button></div></li>)}</ol>}{loaded && nextCursor && <Button variant="secondary" className="mt-4" disabled={busy !== null || moreLoading} onClick={loadOlder}>{moreLoading && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Load more jobs</Button>}</section>;
}

export function MembershipInvitationInbox({ invitations, loaded, loadFailed, nextCursor, busy, refresh, loadOlder, accept }: { invitations: OrganizationMembershipInvitation[]; loaded: boolean; loadFailed: boolean; nextCursor: string | null; busy: string | null; refresh: () => void; loadOlder: () => void; accept: (invitation: OrganizationMembershipInvitation) => Promise<void> }) {
  return <section className="mt-8 rounded-[1.5rem] border border-acid/20 bg-acid/[.035] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Private membership inbox</p><h2 className="mt-2 text-xl font-semibold text-white">Invitations for this signed-in human</h2><p className="mt-1 text-sm leading-6 text-mist">Only invitations addressed to your authenticated account are returned. Accepting one never grants an agent membership authority.</p></div><Button variant="secondary" disabled={busy !== null} onClick={refresh}>{busy === "invitations" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Refresh</Button></div>{!loaded ? <p role="status" className="mt-5 text-sm text-mist">{loadFailed ? "Invitations could not be loaded. No empty state is assumed; use Refresh to retry." : "Loading your private invitations…"}</p> : invitations.length === 0 ? <p className="mt-5 text-sm text-mist">No pending invitations.</p> : <ol className="mt-5 grid gap-3 md:grid-cols-2">{invitations.map((invitation) => <li key={invitation.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="font-semibold text-white">{invitation.organizationName}</p><p className="mt-1 text-xs text-mist">{invitation.organizationSlug} · {invitation.role} · invited {formatDate(invitation.createdAt)}</p><Button className="mt-4" disabled={busy !== null} onClick={() => void accept(invitation)}>{busy === invitation.id && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Accept as signed-in human</Button></li>)}</ol>}{loaded && nextCursor && <Button variant="secondary" className="mt-4" disabled={busy !== null} onClick={loadOlder}>{busy === "invitations-more" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Load older invitations</Button>}</section>;
}

export function OrganizationMemberInventory({ organization, members, nextCursor, busy, refresh, loadOlder, remove }: { organization: Organization; members: OrganizationInvitation[]; nextCursor: string | null; busy: string | null; refresh: () => void; loadOlder: () => void; remove: (member: OrganizationInvitation) => Promise<void> }) {
  return <section className="rounded-xl border border-white/10 bg-panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Member authority</h2><p className="mt-1 text-sm leading-6 text-mist">Owner-only inventory for {organization.name}. It includes pending and accepted non-owner memberships without raw account identifiers.</p></div><Button variant="secondary" disabled={busy !== null} onClick={refresh}>{busy === "members" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Load members</Button></div>{members.length === 0 ? <p className="mt-5 text-sm text-mist">No member records loaded.</p> : <ol className="mt-5 space-y-3">{members.map((member) => <li key={member.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="break-all text-sm font-semibold text-white">{member.memberProfileHandle ? `@${member.memberProfileHandle}` : `Membership ${member.id}`}</p><p className="mt-1 text-xs text-mist">{member.role} · {member.status} · {formatDate(member.createdAt)}</p></div><Button variant="danger" disabled={busy !== null} onClick={() => void remove(member)}>{busy === member.id ? <LoaderCircle className="size-4 animate-spin" aria-hidden /> : <UserMinus className="size-4" aria-hidden />} Remove</Button></div></li>)}</ol>}{nextCursor && <Button variant="secondary" className="mt-4" disabled={busy !== null} onClick={loadOlder}>{busy === "members-more" && <LoaderCircle className="size-4 animate-spin" aria-hidden />} Load older members</Button>}</section>;
}

function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString(); }
